name: Build & Run Tests CashFlow Api

trigger:
- development

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: build

- task: DotNetCoreCLI@2
  displayName: Run Unit & Integration Tests
  inputs:
    command: test

