//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlow.Domain.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceReportGenerationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ResourceReportGenerationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("CashFlow.Domain.Reports.ResourceReportGenerationMessages", typeof(ResourceReportGenerationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public static string AMOUNT => ResourceManager.GetString("AMOUNT", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string DATE => ResourceManager.GetString("DATE", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string DESCRIPTION => ResourceManager.GetString("DESCRIPTION", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PAYMENT_TYPE => ResourceManager.GetString("PAYMENT_TYPE", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string TITLE => ResourceManager.GetString("TITLE", resourceCulture);

	}
}