//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlow.Exception {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorsMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ResourceErrorsMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("CashFlow.Exception.ResourceErrorsMessage", typeof(ResourceErrorsMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		public static string UNKNOWN_ERROR => ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);

		public static string TITLE_REQUIRED => ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string AMOUNT_MUST_BE_GREATER_THAN_ZERO => ResourceManager.GetString("AMOUNT_MUST_BE_GREATER_THAN_ZERO", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EXPENSES_CANNOT_BE_FOR_THE_FUTURE => ResourceManager.GetString("EXPENSES_CANNOT_BE_FOR_THE_FUTURE", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PAYMENT_TYPE_INVALID => ResourceManager.GetString("PAYMENT_TYPE_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EXPENSE_NOT_FOUND => ResourceManager.GetString("EXPENSE_NOT_FOUND", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_PASSWORD => ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_EMPTY => ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_INVALID => ResourceManager.GetString("EMAIL_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NAME_EMPTY => ResourceManager.GetString("NAME_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_ALREADY_REGISTERED => ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_OR_PASSWORD_INVALID => ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD => ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string TAG_TYPE_NOT_SUPPORTED => ResourceManager.GetString("TAG_TYPE_NOT_SUPPORTED", resourceCulture);

	}
}